# Generated by Django 5.1.4 on 2026-09-22 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LightCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_code', models.CharField(max_length=40, unique=True, verbose_name='灯号')),
                ('waterway', models.CharField(max_length=80, verbose_name='所在水道')),
                ('nominal_cd', models.FloatField(verbose_name='标称坎德拉')),
                ('created_by', models.CharField(max_length=64, verbose_name='建卡人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['aid_code'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_cd', models.FloatField(verbose_name='实测光强')),
                ('required_cd', models.FloatField(verbose_name='要求光强')),
                ('bearing_error_deg', models.FloatField(verbose_name='方位偏差')),
                ('verdict', models.CharField(max_length=20, verbose_name='结论')),
                ('note', models.CharField(max_length=200, verbose_name='说明')),
                ('created_by', models.CharField(max_length=64, verbose_name='登记人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='inspection.lightcard', verbose_name='台账卡')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
