# Generated by Django 5.1.4 on 2026-09-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_code', models.CharField(max_length=40, unique=True, verbose_name='灯号')),
                ('waterway', models.CharField(max_length=80, verbose_name='所在水道')),
                ('nominal_cd', models.FloatField(verbose_name='标称坎德拉')),
                ('created_by', models.CharField(max_length=64, verbose_name='建卡人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['aid_code'],
            },
        ),
    ]
